<div class="facet">
  <form name="<?=$this->escapeHtmlAttr($this->title)?>Filter" id="<?=$this->escapeHtmlAttr($this->title)?>Filter">
    <?=$results->getUrlQuery()->asHiddenFields(['page' => "/./", 'filter' => "/^{$this->title}:.*/"])?>
    <input type="hidden" name="<?=$this->escapeHtmlAttr($this->facet['type'])?>range[]" value="<?=$this->escapeHtmlAttr($this->title)?>"/>
    <div class="date-fields">
      <?php $extraInputAttribs = ($this->facet['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
      <div class="date-from">
        <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($this->title)?>from" id="<?=$this->escapeHtmlAttr($this->title)?>from" value="<?=isset($this->facet['values'][0])?$this->escapeHtmlAttr($this->facet['values'][0]):''?>" <?=$extraInputAttribs?>/>
      </div>
	  <div>-</div>
      <div class="date-to">
        <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($this->title)?>to" id="<?=$this->escapeHtmlAttr($this->title)?>to" value="<?=isset($this->facet['values'][1])?$this->escapeHtmlAttr($this->facet['values'][1]):''?>" <?=$extraInputAttribs?>/>
      </div>
    </div>
	<div>
		<input class="btn btn-default" type="submit" value="<?=$this->transEsc('Apply')?>"/>
	</div>
    <?php if ($this->facet['type'] == 'date'): ?>
      <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($this->title)?><?=$this->escapeHtml($this->facet['type'])?>Slider"/></div>
	  <div><a id='linkLast2'>Last 2 years</a></div>
	  <div><a id='linkLast5'>Last 5 years</a></div>
	  <div><a id='linkLast10'>Last 10 years</a></div>
    <?php endif; ?>
  </form>
</div>
<?php if ($this->facet['type'] == 'date'): ?>
  <?php
	$currentYear = date('Y', time());
	$last2Year = strtotime ( '-2 year' , strtotime ( $currentYear ) ) ;
	$last2Year = date ( 'Y' , $last2Year );
	$last5Year = strtotime ( '-5 year' , strtotime ( $currentYear ) ) ;
	$last5Year = date ( 'Y' , $last5Year );
	$last10Year = strtotime ( '-10 year' , strtotime ( $currentYear ) ) ;
	$last10Year = date ( 'Y' , $last10Year );

    $script = <<<JS
$('#linkLast2').click(function(){
	$('#{$this->escapeHtmlAttr($this->title)}from').val($last2Year);
	$('#{$this->escapeHtmlAttr($this->title)}to').val($currentYear);
	$('#{$this->escapeHtmlAttr($this->title)}Filter').submit();
});

$('#linkLast5').click(function(){
	$('#{$this->escapeHtmlAttr($this->title)}from').val($last5Year);
	$('#{$this->escapeHtmlAttr($this->title)}to').val($currentYear);
	$('#{$this->escapeHtmlAttr($this->title)}Filter').submit();
});

$('#linkLast10').click(function(){
	$('#{$this->escapeHtmlAttr($this->title)}from').val($last10Year);
	$('#{$this->escapeHtmlAttr($this->title)}to').val($currentYear);
	$('#{$this->escapeHtmlAttr($this->title)}Filter').submit();
});

JS;
  ?>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<?php endif; ?>
