<h4><?=$this->transEsc('Similar Items')?></h4>
<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <ul class="list-group">
    <?php foreach ($similarRecords as $data): ?>
      <li class="list-group-item">
        <?php $formats = $data->getFormats(); ?>
        <a href="<?=$this->recordLink()->getUrl($data)?>">
          <?=$this->escapeHtml($data->getTitle())?>
        </a>
        <?php $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
           (<?=$this->escapeHtml($pubDates[0])?>)
        <?php endif; ?>
		<?php $authors = $data->getPrimaryAuthors(); if (!empty($authors)): ?>
          <?=$this->transEsc('by')?> <?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
