<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <p><?=$this->transEsc('Search Options')?></p>
      <ul>
        <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
        <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p><?=$this->transEsc('Need Help?')?></p>
      <ul>
        <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
		<li><a href="https://library.aut.ac.nz/">AUT Library website</a></li
      </ul>
    </div>
  </div>
  <div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div>
</footer>
